adding protection against running the script without a valid ssh agent
git-svn-id: http://svn.wikimedia.org/svnroot/mediawiki/trunk@93868 dd0e9695-b195-4be7-bd10-2dea1a65a6b6

diff --git a/debs/wikimedia-task-dns-auth/authdns-update b/debs/wikimedia-task-dns-auth/authdns-update
--- a/debs/wikimedia-task-dns-auth/authdns-update
+++ b/debs/wikimedia-task-dns-auth/authdns-update
@@ -38,6 +38,14 @@ while [ -n "$1" ]; do
 	shift
 done
 
+if ssh-add -l>/dev/null 2>&1
+then
+    echo "Found your ssh agent."
+else
+    echo "Can't contact your ssh agent.  You must forward your ssh agent to use this script."
+    exit 2
+fi
+
 echo "Will skip slave(s) $SKIP."
 
 # export the current templates from svn
