* Removed damaging quotes around for loop array (only worked when there was one item) * Avoid use of old-fashioned backticks for command output capturing * Renamed $IP var to $mwIP
git-svn-id: http://svn.wikimedia.org/svnroot/mediawiki/trunk@97116 dd0e9695-b195-4be7-bd10-2dea1a65a6b6

diff --git a/debs/wikimedia-task-appserver/scap-1skins b/debs/wikimedia-task-appserver/scap-1skins
--- a/debs/wikimedia-task-appserver/scap-1skins
+++ b/debs/wikimedia-task-appserver/scap-1skins
@@ -1,8 +1,12 @@
 #!/bin/bash
 
-mwVersionNums=`mwversionsinuse`
-for mwVerNum in "${mwVersionNums[@]}"
-do
+mwVersionNums=$(mwversionsinuse)
+if [ -z "$mwVersionNums" ]; then
+	echo "Unable to read wikiversions.dat or it is empty"
+	exit 1
+fi
+
+for mwVerNum in ${mwVersionNums[@]}; do
 	sudo -u mwdeploy sh -c "
 	rsync -a --no-perms 10.0.5.8::common/php-$mwVerNum/skins/ \
 	/usr/local/apache/common-local/php-$mwVerNum/skins && \
