* Sync script updates for improved privilege separation. A new user (mwdeploy) is created, which owns all the files in common-local. The texvc install is run as this user. Previously there was a potential for privilege escalation when root users executed scripts which were writable by wikidev. Now the scripts are only run as the unprivileged user, mwdeploy. * Merged sync-common-all and scap. The distinction was pretty stupid to start with, and only got more stupid as time went by, as functionality was copied from scap to sync-common-all. * Installed texvc to a directory writable by mwdeploy, instead of to /usr/local/bin. We would have needed to change the directory for HetDeploy anyway.
git-svn-id: http://svn.wikimedia.org/svnroot/mediawiki/trunk@91703 dd0e9695-b195-4be7-bd10-2dea1a65a6b6

diff --git a/debs/wikimedia-task-appserver/scap-1 b/debs/wikimedia-task-appserver/scap-1
--- a/debs/wikimedia-task-appserver/scap-1
+++ b/debs/wikimedia-task-appserver/scap-1
@@ -1,14 +1,20 @@
 #!/bin/sh
 
-# Compile as regular user
-echo -n Compiling texvc... 
-[ -d /var/tmp/texvc ] || mkdir /var/tmp/texvc
-rsync -r --exclude=.svn/ 10.0.5.8::common/php-1.17/math/ /var/tmp/texvc
-cd /var/tmp/texvc
-make -f Makefile texvc >/dev/null 2>/dev/null && echo ok || echo failed
+if [ ! -d /usr/local/apache/common-local ];then
+	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/common-local; then
+		echo "Unable to create common-local, please re-run this script as root."
+		exit 1
+	fi
+fi
 
-# Copy and install as root
-sudo /usr/sbin/scap-2
+if [ ! -d /usr/local/apache/uncommon ];then
+	if ! install -d -o mwdeploy -g mwdeploy /usr/local/apache/uncommon; then
+		echo "Unable to create /usr/local/apache/uncommon, please re-run this script as root."
+		exit 1
+	fi
+fi
+
+sudo -u mwdeploy /usr/bin/scap-2
 
 echo Done
 
